bank/bank/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bankapp.urls')),
    path('cred/',include('cred.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bank/bankapp/urls.py
from django import views
from django.urls import path
from . import views
app_name='home'
urlpatterns = [

    path('',views.demo,name='demo'),
]

bank/cred/urls.py
from . import views
from django.urls import path
app_name='bank'
urlpatterns=[

    path('but/',views.but,name='but'),
    path('form/',views.form,name='form'),
    path('formm/',views.formm,name='formm'),
    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout')
]

bank/bankapp/models.py
from django.db import models

# Create your models here.
from django.db import models

# Create your models here.
class place(models.Model):
    name=models.CharField(max_length=250)
    image=models.ImageField(upload_to='pics')
    desc=models.TextField()


    def __str__(self):
        return self.name

bank/cred/models.py
from django.db import models

# Create your models here.

bank/bankapp/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import place

# Create your views here.
def demo(request):
    obj=place.objects.all()
    return render(request,"index.html",{'results':obj})





bank/cred/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect


# Create your views here.
def but(request):
    if request.method == "POST":
        return redirect('bank:form')
    return render(request,'button.html')

def form(request):
        return render(request,'form.html')


def formm(request):
    return render(request, 'formm.html')

def login(request):
    if request.method=="POST":
        username=request.POST['username']
        password=request.POST['pass']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect('bank:but')
        else:
            messages.info(request,"invalid")
            return redirect('bank:login')
    return render(request,'login.html')


def logout(request):
    auth.logout(request)
    return redirect('/')



def register(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['pass']
        confirmpass=request.POST['cpass']
        if password==confirmpass:
            if User.objects.filter(username=username).exists():
                messages.info(request,"username already taken")
                return redirect('bank:register')
            # elif User.objects.filter(email=email).exists():
            #     messages.info(request,"email already taken")
                return redirect('register')
            else:
                user = User.objects.create_user(username=username, password=password)
                user.save();

        else:
            messages.info(request, "password not matching")
            return redirect('register')
        return redirect('bank:login')
    return render(request,"reg.html")




bank/templates/about.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="">

  <title> Finexo </title>

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap" rel="stylesheet">

  <!--owl slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />

  <!-- font awesome style -->
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />

</head>

<body class="sub_page">

  <div class="hero_area">

    <div class="hero_bg_box">
      <div class="bg_img_box">
        <img src="{% static 'images/hero-bg.png' %}" alt="">
      </div>
    </div>

    <!-- header section strats -->
    <header class="header_section">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
          <a class="navbar-brand" href="{% static 'index.html' %}">
            <span>
              Finexo
            </span>
          </a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class=""> </span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav  ">
              <li class="nav-item ">
                <a class="nav-link" href="{% static 'index.html' %}">Home </a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% static 'about.html' %}"> About <span class="sr-only">(current)</span> </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% static 'service.html' %}">Services</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% static 'why.html' %}">Why Us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% static 'team.html' %}">Team</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#"> <i class="fa fa-user" aria-hidden="true"></i> Login</a>
              </li>
              <form class="form-inline">
                <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit">
                  <i class="fa fa-search" aria-hidden="true"></i>
                </button>
              </form>
            </ul>
          </div>
        </nav>
      </div>
    </header>
    <!-- end header section -->
  </div>

  <!-- about section -->

  <section class="about_section layout_padding">
    <div class="container  ">
      <div class="heading_container heading_center">
        <h2>
          About <span>Us</span>
        </h2>
        <p>
          Magni quod blanditiis non minus sed aut voluptatum illum quisquam aspernatur ullam vel beatae rerum ipsum voluptatibus
        </p>
      </div>
      <div class="row">
        <div class="col-md-6 ">
          <div class="img-box">
            <img src="{% static 'images/about-img.png' %}" alt="">
          </div>
        </div>
        <div class="col-md-6">
          <div class="detail-box">
            <h3>
              We Are Finexo
            </h3>
            <p>
              There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration
              in some form, by injected humour, or randomised words which don't look even slightly believable. If you
              are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in
              the middle of text. All
            </p>
            <p>
              Molestiae odio earum non qui cumque provident voluptates, repellendus exercitationem, possimus at iste corrupti officiis unde alias eius ducimus reiciendis soluta eveniet. Nobis ullam ab omnis quasi expedita.
            </p>
            <a href="">
              Read More
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end about section -->

  <!-- info section -->

  <section class="info_section layout_padding2">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-lg-3 info_col">
          <div class="info_contact">
            <h4>
              Address
            </h4>
            <div class="contact_link_box">
              <a href="">
                <i class="{% static 'fa fa-map-marker' %}" aria-hidden="true"></i>
                <span>
                  Location
                </span>
              </a>
              <a href="">
                <i class="{% static 'fa fa-phone' %}" aria-hidden="true"></i>
                <span>
                  Call +01 1234567890
                </span>
              </a>
              <a href="">
                <i class="{% static 'fa fa-envelope' %}" aria-hidden="true"></i>
                <span>
                  demo@gmail.com
                </span>
              </a>
            </div>
          </div>
          <div class="info_social">
            <a href="">
              <i class="{% static 'fa fa-facebook' %}" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="{% static 'fa fa-twitter' %}" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="{% static 'fa fa-linkedin' %}" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="{% static 'fa fa-instagram' %}" aria-hidden="true"></i>
            </a>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 info_col">
          <div class="info_detail">
            <h4>
              Info
            </h4>
            <p>
              necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful
            </p>
          </div>
        </div>
        <div class="col-md-6 col-lg-2 mx-auto info_col">
          <div class="info_link_box">
            <h4>
              Links
            </h4>
            <div class="info_links">
              <a class="active" href="{% static 'index.html' %}">
                Home
              </a>
              <a class="" href="about.html">
                About
              </a>
              <a class="" href="service.html">
                Services
              </a>
              <a class="" href="why.html">
                Why Us
              </a>
              <a class="" href="team.html">
                Team
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3 info_col ">
          <h4>
            Subscribe
          </h4>
          <form action="#">
            <input type="text" placeholder="Enter email" />
            <button type="submit">
              Subscribe
            </button>
          </form>
        </div>
      </div>
    </div>
  </section>

  <!-- end info section -->

  <!-- footer section -->
  <section class="footer_section">
    <div class="container">
      <p>
        &copy; <span id="displayYear"></span> All Rights Reserved By
        <a href="{% static 'https://html.design/' %}">Fincorp</a>
      </p>
    </div>
  </section>
  <!-- footer section -->

  <!-- jQery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- popper js -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <!-- bootstrap js -->
  <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
  <!-- owl slider -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
  </script>
  <!-- custom js -->
  <script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
  <!-- Google Map -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap">
  </script>
  <!-- End Google Map -->

</body>

</html>

bank/templates/form.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
     <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

        <script>
var subjectObject = {
  "ALAPPUZHA": {
    "AROOR": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
    "CHERTHALA": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
    "THURAVOOR": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
    "KAYAMKULAM": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
  },
  "ERNAKULAM": {
    "ANGAMALY": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
    "KOCHI": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
    "KAKKANAD": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
  },
  "IDUKKI": {
    "MUNNAR": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
    "THODUPUZHA": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
    "CHERUTHONI": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
  },
  "KANNUR": {
    "PAYYANUR": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
    "TALIPARAMBU": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
    "THALASHERRY": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
  },
  "KASARAGOD": {
    "CHERKALA": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
    "MANJESHWAR": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
    "THATTUMAL": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
  },
  "KOLLAM": {
    "KOTTARAKARA": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
    "MAYYANAD": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
    "OACHIRA": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
  },
  "KOTTAYAM": {
    "CHANGANASHERRY": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
    "KANJIRAPALLI": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
    "VAIKOM": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
  },
  "KOZHIKHODE": {
    "BALUSHERRY": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
    "CHERUVANNUR": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
    "KOYILANDY": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
  },
  "MALAPPURAM": {
    "PONNANI": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
    "TANUR": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
    "VALANCHERY": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
  },
  "PALAKKAD": {
    "CHITTUR": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
    "OTTAPALAM": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
    "SHORNUR": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
  },
  "PATHANAMTHITTA": {
    "ADOOR": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
    "PANDALAM": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
    "THIRUVALLA": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
  },
  "THIRUVANANTHAPURAM": {
    "ATTINGAL": ["current account", "savings account", "fixed account"],
    "NEYYATINGARA": ["current account", "savings account", "fixed account"],
    "VARKALA": ["current account", "savings account", "fixed account"],
  },
  "THRISSUR": {
    "CHAVAKKAD": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
    "CHALAKUDY": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
    "GURUVAYUR": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
  },
  "WAYANAD": {
    "KALPETTA": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
    "MANATHAVADY": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
    "SULTHAN BATHERY": ["CURRENT ACCOUNT", "SAVINGS ACCOUNT", "FIXED ACCOUNT"],
  },
}
window.onload = function() {
  var subjectSel = document.getElementById("subject");
  var topicSel = document.getElementById("topic");
  var chapterSel = document.getElementById("chapter");
  for (var x in subjectObject) {
    subjectSel.options[subjectSel.options.length] = new Option(x, x);
  }
  subjectSel.onchange = function() {

 chapterSel.length = 1;
 topicSel.length = 1;
    //display correct values
    for (var y in subjectObject[this.value]) {
      topicSel.options[topicSel.options.length] = new Option(y, y);
    }
  }
  topicSel.onchange = function() {
 chapterSel.length = 1;
    //display correct values
    var z = subjectObject[subjectSel.value][this.value];
    for (var i = 0; i < z.length; i++) {
      chapterSel.options[chapterSel.options.length] = new Option(z[i], z[i]);
    }
  }
}
</script>
<style>
body {
  font-family: Arial, Helvetica, sans-serif;
  background-color: white;
  width:1200px;
  padding-left:200px;
}

* {
  box-sizing: border-box;
}

/* Add padding to containers */
.container {
  padding: 16px;
  background-color: white;
}

/* Full-width input fields */
input[type=text], input[type=password] {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

/* Overwrite default styles of hr */
hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}

select {
  width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;
}

input[type=text]:focus, input[type=password]:focus {
  background-color: #ddd;
  outline: none;
}

/* Set a style for the submit button */
.registerbtn {
  background-color: #04AA6D;
  color: white;
  padding: 16px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
  padding-left:10;
}

.registerbtn:hover {
  opacity: 1;
}
.logoutbtnn {
  background-color: slateblue;
  color: white;
  padding: 16px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
  padding-left:10;
}

.logoutbtnn:hover {
  opacity: 1;
}

.registerbtn {
  background-color: #04AA6D;
  color: white;
  padding: 16px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
  padding-left:10;
}

/* Add a blue text color to links */
a {
  color: dodgerblue;
}

/* Set a grey background color and center the text of the "sign in" section */
.signin {
  background-color: #f1f1f1;
  text-align: center;
}

.ab{
background-color:lightpink;
}




</style>
</head>
<body>

    <h1>ALPHA BANK</h1>


<form method="post" action="{% url 'bank:formm' %}">
    {% csrf_token %}
  <div class="container ab">
    <center><h1>Register Form</h1></center>

    <p>Please fill in this form to create an account.</p>
    <hr>

    <label for="email"><b>NAME</b></label>
    <input type="text" placeholder="Enter Name" name="email" id="email" >

    <label for="psw"><b>DOB</b></label>
    <input type="text" placeholder="Enter Date Of Birth" name="psw" id="psw" >
<br>
      <label for="email"><b>AGE</b></label>
    <input type="text" placeholder="Enter Age" name="email" id="email" >

      <br>
      <label for="email"><b>GENDER</b></label><br><br>
    <input type="radio"  name="gen" value="Male" >MALE
      <input type="radio" name="gen" value="Female">FEMALE
      <input type="radio" name="gen" value="Female">OTHERS

      <br><br>
      <label for="email"><b>PHONE NUMBER</b></label>
    <input type="text" placeholder="Enter Your Number" name="email" id="email" >

      <br>
      <label for="email"><b>EMAIL</b></label>
    <input type="text" placeholder="Enter Email" name="email" id="email" >

   <br>
      <label for="email"><b>ADDRESS</b></label>
    <input type="text" placeholder="Enter Address" name="email" id="email">

<!--      <label for="email"><b>DISTRICT</b></label><br>-->

<!--      <select id="country-state" name="district">-->
<!--    <option value="">Select district</option>-->
<!--    <option value="AL">Alappuzha</option>-->
<!--    <option value="ER">Ernakulam</option>-->
<!--    <option value="KO">Kollam</option>-->
<!--    <option value="TH">Thrissur</option>-->
<!--    <option value="ID">Idukki</option>-->

<!--</select>-->
<!--<br><br>-->
<!--      <label for="email"><b>BRANCH</b></label><br>-->
<!--      <select id="AL" name="district">-->
<!--    <option value="">Select Branch</option>-->
<!--    <option value="ar">Aroor</option>-->
<!--    <option value="ch">Cherthala</option>-->
<!--     <option value="th">Thuravoor</option>-->
<!--     <option value="ka">Kayamkulam</option>-->
<!--</select>-->

<div name="form1" id="form1" >
<label for="email"><b>DISTRICT</b></label> <select name="subject" id="subject">
<!--    <option value="" selected="selected">Select District</option>-->
    <option value="" >Select </option>
  </select>
  <br><br>
<label for="email"><b>BRANCHES</b></label> <select name="topic" id="topic">
    <option value="" selected="selected">Please select District first</option>
  </select>
  <br><br>
<label for="email"><b>ACCOUNT TYPE</b></label> <select name="chapter" id="chapter">
    <option value="" selected="selected">Please select district and branch first</option>
  </select>
  <br><br>
</div>

      <br>
      <label for="email"><b>MATERIALS PROVIDE</b></label><br><br>
      Debit Card<input type="checkbox" name="mp" value="Debit Card">
      Credit Card<input type="checkbox" name="mp" value="Credit Card">
      Cheque Book<input type="checkbox" name="mp" value="Cheque Book">


    <hr>
<div >
    <button type="submit" class="registerbtn">Submit</button>
      <button type="reset"  class="logoutbtnn">logout</button>
  </div>

<!--  <div class="container signin">-->
<!--    <p>Already have an account? <a href="#">Sign in</a>.</p>-->
  </div>
</form>

</body>
</html>

bank/templates/formm.html
{% load static %}
<head>
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
<style>
    body {
    background-color:lightgreen;
    }
</style>
</head>
<br>
<br>
<br>
<br>
<body bgcolor="lightgreen">
<center>
<h1>ACCOUNT CREATED SUCCESSFULLY</h1>
    <form method="post">
               {% csrf_token %}
            <a href="/">
              HOME
            </a>
              </form>
    </center>


</body>